# Generated by Django 6.0.3 on 2026-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancellery', '0002_pen_delete_chancellery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='pen_type',
            field=models.CharField(choices=[('ballpoint', 'Шариковая'), ('gel', 'Гелевая'), ('fountain', 'Перьевая'), ('roller', 'Роллер')], default='ballpoint', max_length=20),
        ),
        migrations.AddField(
            model_name='pen',
            name='sku',
            field=models.CharField(default='temp', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
